_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  comment: 0
  config: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  drupalup_block: 0
  drupalup_controller: 0
  drupalup_fibo: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  image_captcha: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  locale: 0
  loremipsum: 0
  masquerade: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  module_filter: 0
  module_hero: 0
  mymodule: 0
  node: 0
  options: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  reroute_email: 0
  rsvplist: 0
  scheduler: 0
  shortcut: 0
  simple_gmap: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  video_embed_field: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  votingapi: 0
  webprofiler: 0
  pathauto: 1
  views: 10
  oddprofile: 1000
theme:
  seven: 0
  oddbaby: 0
  bartik: 0
  olivero: 0
profile: oddprofile
