_core:
  default_config_hash: sUlarU5ZDyvvs9Eo8Soyt2wHDGO1-nCAeQuuH3zeee4
loremipsum:
  page_title: 'Lorem ipsum'
  source_text: "Lorem ipsum dolor sit amet, consectetur adipisci elit, sed do  eiusmod tempor incididunt ut labore et dolore magna aliqua. \r\nUt enim ad minim  veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo  consequat. \r\nDuis aute irure dolor in reprehenderit in voluptate velit esse  cillum dolore eu fugiat nulla pariatur. \r\nExcepteur sint occaecat cupidatat non  proident, sunt in culpa qui officia deserunt mollit anim id est laborum. "
